from src.record import (
    BIRTHDAY_NOT_VALID_ERROR,
    NAME_NOT_VALID_ERROR,
    PHONE_ALREADY_EXISTS_ERROR,
    PHONE_NOT_FOUND_ERROR,
    PHONE_NOT_VALID_ERROR,
)

RECORD_ERRORS = {
    "PHONE_NOT_VALID": PHONE_NOT_VALID_ERROR,
    "NAME_NOT_VALID": NAME_NOT_VALID_ERROR,
    "PHONE_NOT_FOUND": PHONE_NOT_FOUND_ERROR,
    "BIRTHDAY_NOT_VALID": BIRTHDAY_NOT_VALID_ERROR,
    "PHONE_ALREADY_EXISTS": PHONE_ALREADY_EXISTS_ERROR,
}

INVALID_PHONE_12 = "123456789012"
INVALID_PHONE_15 = "123456789012345"
